<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Booking Confirmation</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1f2937; }
        .header, .footer { margin-bottom: 16px; }
        .title { font-size: 20px; font-weight: 700; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #d1d5db; padding: 6px; text-align: left; }
        .muted { color: #6b7280; }
    </style>
</head>
<body>
@php
    $bs = $booking->agency->agencySetting;
    $brandName = $bs?->display_name ?: $booking->agency->name;
    $supportEmail = $bs?->support_email ?: ($booking->agency->settings['support_email'] ?? 'support@example.com');
    $supportPhone = $bs?->support_phone ?: ($booking->agency->settings['support_phone'] ?? 'N/A');
    $footerText = $bs?->footer_copyright ?: 'Generated by Hayat Travel Solutions OTA platform.';
@endphp
<div class="header">
    <div class="title">{{ $brandName }}</div>
    <div>{{ $supportEmail }} | {{ $supportPhone }}</div>
    <h2>Booking Confirmation</h2>
    <div class="muted">Number: {{ $documentNumber }}</div>
</div>
<p><strong>Booking Reference:</strong> {{ $booking->booking_reference ?? 'N/A' }}</p>
<p><strong>Route:</strong> {{ $booking->route ?? 'N/A' }}</p>
<p><strong>Status:</strong> {{ str_replace('_', ' ', $booking->status->value) }}</p>
<h3>Passengers</h3>
<table>
    <thead><tr><th>Name</th><th>Title</th></tr></thead>
    <tbody>
    @foreach($booking->passengers as $passenger)
        <tr><td>{{ $passenger->first_name }} {{ $passenger->last_name }}</td><td>{{ $passenger->title }}</td></tr>
    @endforeach
    </tbody>
</table>
<div class="footer muted">
    Generated on {{ $generatedAt->format('Y-m-d H:i') }}<br>
    {{ $footerText }}
</div>
</body>
</html>
