<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1f2937; }
        .title { font-size: 20px; font-weight: 700; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #d1d5db; padding: 6px; text-align: left; }
        .muted { color: #6b7280; }
    </style>
</head>
<body>
@php
    $bs = $booking->agency->agencySetting;
    $brandName = $bs?->display_name ?: $booking->agency->name;
    $supportEmail = $bs?->support_email ?: ($booking->agency->settings['support_email'] ?? 'support@example.com');
    $supportPhone = $bs?->support_phone ?: ($booking->agency->settings['support_phone'] ?? 'N/A');
    $footerText = $bs?->footer_copyright ?: 'Generated by Hayat Travel Solutions OTA platform.';
@endphp
<div class="title">{{ $brandName }}</div>
<div>{{ $supportEmail }} | {{ $supportPhone }}</div>
<h2>Invoice</h2>
<div class="muted">Number: {{ $documentNumber }}</div>
<p><strong>Booking Reference:</strong> {{ $booking->booking_reference ?? 'N/A' }}</p>
<p><strong>Route:</strong> {{ $booking->route ?? 'N/A' }}</p>
<h3>Fare Details</h3>
<table>
    <tbody>
    <tr><th>Base Fare</th><td>{{ number_format((float) ($booking->fareBreakdown?->base_fare ?? 0), 2) }}</td></tr>
    <tr><th>Taxes</th><td>{{ number_format((float) ($booking->fareBreakdown?->taxes ?? 0), 2) }}</td></tr>
    <tr><th>Fees</th><td>{{ number_format((float) ($booking->fareBreakdown?->fees ?? 0), 2) }}</td></tr>
    <tr><th>Total</th><td>{{ number_format((float) ($booking->fareBreakdown?->total ?? 0), 2) }} {{ $booking->currency }}</td></tr>
    </tbody>
</table>
<div class="muted">
    Generated on {{ $generatedAt->format('Y-m-d H:i') }}<br>
    {{ $footerText }}
</div>
</body>
</html>
