<?php

use App\Http\Controllers\Admin\AdminSectionController;
use App\Http\Controllers\Admin\AgencyBrandingController;
use App\Http\Controllers\Admin\AgencyCommunicationSettingsController;
use App\Http\Controllers\Admin\AgencyHomepageController;
use App\Http\Controllers\Admin\AgencyMediaController;
use App\Http\Controllers\Admin\AgencyMessageTemplateController;
use App\Http\Controllers\Admin\AgentApplicationController;
use App\Http\Controllers\Admin\AgentCommissionController;
use App\Http\Controllers\Admin\BookingCancellationController;
use App\Http\Controllers\Admin\BookingManagementController;
use App\Http\Controllers\Admin\BookingPaymentController;
use App\Http\Controllers\Admin\BookingRefundController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\MarkupRuleController;
use App\Http\Controllers\Admin\SupplierConnectionController;
use App\Http\Controllers\Admin\SystemSafetyController;
use App\Http\Controllers\Admin\UserManagementController;
use App\Http\Controllers\BookingDocumentController;
use App\Http\Controllers\BookingTicketingController;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->name('admin.')->group(function (): void {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('/bookings', [BookingManagementController::class, 'index'])->name('bookings');
    Route::get('/bookings/{booking}', [BookingManagementController::class, 'show'])->name('bookings.show');
    Route::patch('/bookings/{booking}/status', [BookingManagementController::class, 'updateStatus'])->name('bookings.status');
    Route::post('/bookings/{booking}/notes', [BookingManagementController::class, 'storeNote'])->name('bookings.notes');
    Route::patch('/bookings/{booking}/assign-staff', [BookingManagementController::class, 'assignStaff'])->name('bookings.assign-staff');
    Route::post('/bookings/{booking}/supplier-booking', [BookingManagementController::class, 'createSupplierBooking'])->name('bookings.supplier-booking');
    Route::post('/bookings/{booking}/payments', [BookingPaymentController::class, 'store'])->name('bookings.payments.store');
    Route::patch('/bookings/payments/{bookingPayment}/verify', [BookingPaymentController::class, 'verify'])->name('bookings.payments.verify');
    Route::patch('/bookings/payments/{bookingPayment}/reject', [BookingPaymentController::class, 'reject'])->name('bookings.payments.reject');
    Route::post('/bookings/{booking}/cancellations', [BookingCancellationController::class, 'store'])->name('bookings.cancellations.store');
    Route::patch('/bookings/cancellations/{cancellationRequest}/approve', [BookingCancellationController::class, 'approve'])->name('bookings.cancellations.approve');
    Route::patch('/bookings/cancellations/{cancellationRequest}/reject', [BookingCancellationController::class, 'reject'])->name('bookings.cancellations.reject');
    Route::patch('/bookings/cancellations/{cancellationRequest}/process', [BookingCancellationController::class, 'process'])->name('bookings.cancellations.process');
    Route::post('/bookings/{booking}/refunds', [BookingRefundController::class, 'store'])->name('bookings.refunds.store');
    Route::patch('/bookings/refunds/{bookingRefund}/approve', [BookingRefundController::class, 'approve'])->name('bookings.refunds.approve');
    Route::patch('/bookings/refunds/{bookingRefund}/mark-paid', [BookingRefundController::class, 'markPaid'])->name('bookings.refunds.mark-paid');
    Route::patch('/bookings/refunds/{bookingRefund}/reject', [BookingRefundController::class, 'reject'])->name('bookings.refunds.reject');
    Route::post('/bookings/{booking}/issue-ticket', [BookingTicketingController::class, 'issue'])->name('bookings.issue-ticket');
    Route::post('/bookings/{booking}/documents/confirmation', [BookingDocumentController::class, 'bookingConfirmation'])->name('bookings.documents.confirmation');
    Route::post('/bookings/{booking}/documents/invoice', [BookingDocumentController::class, 'invoice'])->name('bookings.documents.invoice');
    Route::post('/bookings/{booking}/documents/ticket-itinerary', [BookingDocumentController::class, 'ticketItinerary'])->name('bookings.documents.ticket-itinerary');
    Route::post('/bookings/payments/{bookingPayment}/documents/receipt', [BookingDocumentController::class, 'paymentReceipt'])->name('bookings.payments.documents.receipt');
    Route::get('/bookings/documents/{bookingDocument}/download', [BookingDocumentController::class, 'download'])->name('bookings.documents.download');
    Route::get('/commissions', [AgentCommissionController::class, 'index'])->name('commissions.index');
    Route::get('/commissions/{agent}', [AgentCommissionController::class, 'show'])->name('commissions.show');
    Route::post('/commissions/entries/{entry}/approve', [AgentCommissionController::class, 'approve'])->name('commissions.entries.approve');
    Route::post('/commissions/entries/{entry}/reject', [AgentCommissionController::class, 'reject'])->name('commissions.entries.reject');
    Route::post('/commissions/{agent}/adjustments', [AgentCommissionController::class, 'adjustment'])->name('commissions.adjustments.store');
    Route::post('/commissions/{agent}/payouts', [AgentCommissionController::class, 'payout'])->name('commissions.payouts.store');
    Route::post('/commissions/{agent}/statements', [AgentCommissionController::class, 'statement'])->name('commissions.statements.store');
    Route::get('/users', [UserManagementController::class, 'index'])->name('users.index');
    Route::get('/users/create', [UserManagementController::class, 'create'])->name('users.create');
    Route::post('/users', [UserManagementController::class, 'store'])->name('users.store');
    Route::get('/users/{user}', [UserManagementController::class, 'show'])->name('users.show');
    Route::get('/users/{user}/edit', [UserManagementController::class, 'edit'])->name('users.edit');
    Route::patch('/users/{user}', [UserManagementController::class, 'update'])->name('users.update');
    Route::patch('/users/{user}/suspend', [UserManagementController::class, 'suspend'])->name('users.suspend');
    Route::patch('/users/{user}/activate', [UserManagementController::class, 'activate'])->name('users.activate');
    Route::post('/users/{user}/send-invite', [UserManagementController::class, 'sendInvite'])->name('users.send-invite');
    Route::post('/users/{user}/reset-password-link', [UserManagementController::class, 'sendResetPasswordLink'])->name('users.reset-password-link');

    Route::get('/agents', [AdminSectionController::class, 'agents'])->name('agents');
    Route::get('/agent-applications', [AgentApplicationController::class, 'index'])->name('agent-applications.index');
    Route::get('/agent-applications/{application}', [AgentApplicationController::class, 'show'])->name('agent-applications.show');
    Route::patch('/agent-applications/{application}/approve', [AgentApplicationController::class, 'approve'])->name('agent-applications.approve');
    Route::patch('/agent-applications/{application}/reject', [AgentApplicationController::class, 'reject'])->name('agent-applications.reject');
    Route::patch('/agent-applications/{application}/needs-more-info', [AgentApplicationController::class, 'needsMoreInfo'])->name('agent-applications.needs-more-info');
    Route::get('/staff', [AdminSectionController::class, 'staff'])->name('staff');
    Route::get('/markups', [MarkupRuleController::class, 'index'])->name('markups');
    Route::get('/markups/create', [MarkupRuleController::class, 'create'])->name('markups.create');
    Route::post('/markups', [MarkupRuleController::class, 'store'])->name('markups.store');
    Route::get('/markups/{markupRule}/edit', [MarkupRuleController::class, 'edit'])->name('markups.edit');
    Route::patch('/markups/{markupRule}', [MarkupRuleController::class, 'update'])->name('markups.update');
    Route::patch('/markups/{markupRule}/toggle-status', [MarkupRuleController::class, 'toggleStatus'])->name('markups.toggle-status');
    Route::get('/api-settings', [SupplierConnectionController::class, 'index'])->name('api-settings');
    Route::get('/api-settings/create', [SupplierConnectionController::class, 'create'])->name('api-settings.create');
    Route::post('/api-settings', [SupplierConnectionController::class, 'store'])->name('api-settings.store');
    Route::get('/api-settings/{supplierConnection}/edit', [SupplierConnectionController::class, 'edit'])->name('api-settings.edit');
    Route::patch('/api-settings/{supplierConnection}', [SupplierConnectionController::class, 'update'])->name('api-settings.update');
    Route::patch('/api-settings/{supplierConnection}/test', [SupplierConnectionController::class, 'test'])->name('api-settings.test');
    Route::patch('/api-settings/{supplierConnection}/toggle-status', [SupplierConnectionController::class, 'toggleStatus'])->name('api-settings.toggle-status');
    Route::get('/roles-permissions', [AdminSectionController::class, 'rolesPermissions'])->name('roles-permissions');
    Route::get('/reports', [AdminSectionController::class, 'reports'])->name('reports');
    Route::get('/settings/branding', [AgencyBrandingController::class, 'edit'])->name('settings.branding.edit');
    Route::patch('/settings/branding', [AgencyBrandingController::class, 'update'])->name('settings.branding.update');
    Route::get('/settings/homepage', [AgencyHomepageController::class, 'edit'])->name('settings.homepage.edit');
    Route::patch('/settings/homepage/{section}', [AgencyHomepageController::class, 'update'])->name('settings.homepage.update');
    Route::get('/settings/media', [AgencyMediaController::class, 'index'])->name('settings.media.index');
    Route::post('/settings/media', [AgencyMediaController::class, 'store'])->name('settings.media.store');
    Route::delete('/settings/media/{agencyMedia}', [AgencyMediaController::class, 'destroy'])->name('settings.media.destroy');
    Route::get('/settings/communications', [AgencyCommunicationSettingsController::class, 'index'])->name('settings.communications.index');
    Route::patch('/settings/communications', [AgencyCommunicationSettingsController::class, 'update'])->name('settings.communications.update');
    Route::post('/settings/communications/test-email', [AgencyCommunicationSettingsController::class, 'testEmail'])->name('settings.communications.test-email');
    Route::post('/settings/communications/test-whatsapp', [AgencyCommunicationSettingsController::class, 'testWhatsapp'])->name('settings.communications.test-whatsapp');
    Route::get('/settings/communications/templates', [AgencyMessageTemplateController::class, 'index'])->name('settings.communications.templates.index');
    Route::get('/settings/communications/templates/{event}/{channel}/edit', [AgencyMessageTemplateController::class, 'edit'])->name('settings.communications.templates.edit');
    Route::patch('/settings/communications/templates/{event}/{channel}', [AgencyMessageTemplateController::class, 'update'])->name('settings.communications.templates.update');
    Route::get('/system-health', [SystemSafetyController::class, 'systemHealth'])->name('system-health');
    Route::get('/deployment-checklist', [SystemSafetyController::class, 'deploymentChecklist'])->name('deployment-checklist');
    Route::get('/branding', [AdminSectionController::class, 'branding'])->name('branding');
    Route::get('/go-live-checklist', [AdminSectionController::class, 'goLiveChecklist'])->name('go-live-checklist');
});
