<?php

/**
 * Demo-only bookings dataset (no DB). Used by admin dashboard + bookings management UI.
 */
return [
    'stats' => [
        'total_bookings' => 1847,
        'pending_bookings' => 23,
        'active_agents' => 42,
        'monthly_revenue_pkr' => 128450000,
    ],

    /*
    |--------------------------------------------------------------------------
    | Bookings management sample (subset for UI demo)
    |--------------------------------------------------------------------------
    */
    'bookings' => [
        [
            'booking_ref' => 'OTA-99214',
            'customer_name' => 'Ahmed Khan',
            'customer_type' => 'customer',
            'agent_name' => null,
            'route' => 'LHE → DXB',
            'airline' => 'Emirates (EK)',
            'travel_date' => '2026-06-12',
            'passengers_count' => 2,
            'base_fare' => 305000,
            'markup' => 18400,
            'total_fare' => 323400,
            'status' => 'confirmed',
            'payment_status' => 'paid',
            'created_at' => '2026-05-02 14:22',
            'contact_phone' => '+92 300 1122334',
            'contact_email' => 'ahmed.khan@email.com',
            'internal_note' => 'Customer requested aisle seats — notated for ops queue.',
        ],
        [
            'booking_ref' => 'OTA-99213',
            'customer_name' => 'Sara Malik',
            'customer_type' => 'guest',
            'agent_name' => null,
            'route' => 'KHI → DXB',
            'airline' => 'PIA (PK)',
            'travel_date' => '2026-06-18',
            'passengers_count' => 1,
            'base_fare' => 148000,
            'markup' => 17200,
            'total_fare' => 165200,
            'status' => 'pending',
            'payment_status' => 'unpaid',
            'created_at' => '2026-05-02 11:05',
            'contact_phone' => '+92 321 9988776',
            'contact_email' => 'sara.malik@gmail.com',
            'internal_note' => 'Awaiting bank transfer screenshot from guest checkout.',
        ],
        [
            'booking_ref' => 'OTA-99212',
            'customer_name' => 'Hassan Raza',
            'customer_type' => 'agent',
            'agent_name' => 'SkyLink Travels (IATA 9123456)',
            'route' => 'ISB → RUH',
            'airline' => 'Saudia (SV)',
            'travel_date' => '2026-05-28',
            'passengers_count' => 3,
            'base_fare' => 198000,
            'markup' => 14900,
            'total_fare' => 212900,
            'status' => 'ticketed',
            'payment_status' => 'paid',
            'created_at' => '2026-05-01 19:40',
            'contact_phone' => '+92 51 5550123',
            'contact_email' => 'ops@skylinktravels.pk',
            'internal_note' => 'Agency credit applied; commission rule GOLD-2026.',
        ],
        [
            'booking_ref' => 'OTA-99211',
            'customer_name' => 'Fatima Noor',
            'customer_type' => 'customer',
            'agent_name' => null,
            'route' => 'LHE → JED',
            'airline' => 'Saudia (SV)',
            'travel_date' => '2026-07-03',
            'passengers_count' => 1,
            'base_fare' => 182000,
            'markup' => 16750,
            'total_fare' => 198750,
            'status' => 'confirmed',
            'payment_status' => 'partial',
            'created_at' => '2026-05-01 09:15',
            'contact_phone' => '+92 333 4455667',
            'contact_email' => 'fatima.noor@outlook.com',
            'internal_note' => 'Partial received — balance due 72h before departure per policy.',
        ],
        [
            'booking_ref' => 'OTA-99210',
            'customer_name' => 'Omar Siddiqui',
            'customer_type' => 'guest',
            'agent_name' => null,
            'route' => 'LHE → DXB',
            'airline' => 'Emirates (EK)',
            'travel_date' => '2026-04-20',
            'passengers_count' => 2,
            'base_fare' => 176000,
            'markup' => 14200,
            'total_fare' => 190200,
            'status' => 'cancelled',
            'payment_status' => 'refunded',
            'created_at' => '2026-04-30 16:58',
            'contact_phone' => '+92 300 5544332',
            'contact_email' => 'omar.s@yahoo.com',
            'internal_note' => 'Cancelled by customer within free window; refund queued to original card.',
        ],
        [
            'booking_ref' => 'OTA-99209',
            'customer_name' => 'Bilal Hussain',
            'customer_type' => 'agent',
            'agent_name' => 'Crescent Tours',
            'route' => 'LHE → DXB',
            'airline' => 'PIA (PK)',
            'travel_date' => '2026-06-02',
            'passengers_count' => 4,
            'base_fare' => 412000,
            'markup' => 28800,
            'total_fare' => 440800,
            'status' => 'ticketed',
            'payment_status' => 'paid',
            'created_at' => '2026-04-29 10:11',
            'contact_phone' => '+92 42 3765432',
            'contact_email' => 'accounts@crescenttours.pk',
            'internal_note' => 'Large family group — seat allocation pending airline seat map.',
        ],
        [
            'booking_ref' => 'OTA-99208',
            'customer_name' => 'Ayesha Tariq',
            'customer_type' => 'customer',
            'agent_name' => null,
            'route' => 'KHI → DXB',
            'airline' => 'Flydubai (FZ)',
            'travel_date' => '2026-05-15',
            'passengers_count' => 1,
            'base_fare' => 89500,
            'markup' => 6200,
            'total_fare' => 95700,
            'status' => 'pending',
            'payment_status' => 'unpaid',
            'created_at' => '2026-04-28 08:40',
            'contact_phone' => '+92 345 6677889',
            'contact_email' => 'ayesha.t@gmail.com',
            'internal_note' => 'Price-hold expiring EOD — send automated reminder (demo).',
        ],
        [
            'booking_ref' => 'OTA-99207',
            'customer_name' => 'Usman Farooq',
            'customer_type' => 'guest',
            'agent_name' => null,
            'route' => 'ISB → RUH',
            'airline' => 'Saudia (SV)',
            'travel_date' => '2026-06-22',
            'passengers_count' => 2,
            'base_fare' => 221000,
            'markup' => 15800,
            'total_fare' => 236800,
            'status' => 'confirmed',
            'payment_status' => 'unpaid',
            'created_at' => '2026-04-27 17:02',
            'contact_phone' => '+92 51 2003344',
            'contact_email' => 'usman.farooq@proton.me',
            'internal_note' => 'Corporate traveller — VAT invoice requested on confirmation.',
        ],
    ],
];
