<?php

/**
 * Demo-only B2B agents dataset (no DB).
 */
return [
    'demo_note' => 'Agents can create bookings for customers, receive commission, and later use wallet/credit limit features.',

    'agents' => [
        [
            'agent_code' => 'AGT-1001',
            'agency_name' => 'SkyLink Travels (Pvt) Ltd',
            'contact_person' => 'Kamran Abbasi',
            'phone' => '+92 51 5550123',
            'email' => 'ops@skylinktravels.pk',
            'city' => 'Islamabad',
            'commission_plan' => 'Gold tier — 3.0% default on published fare',
            'incentive_type' => 'percentage',
            'total_bookings' => 428,
            'monthly_sales' => 18450000,
            'outstanding_balance' => 420000,
            'status' => 'active',
            'joined_at' => '2024-03-12',
            'last_booking_at' => '2026-05-02 09:40',
            'notes' => 'Primary Gulf routes; strong on LHE/DXB. Credit line reviewed Q1 2026.',
        ],
        [
            'agent_code' => 'AGT-1002',
            'agency_name' => 'Crescent Tours',
            'contact_person' => 'Nadia Sheikh',
            'phone' => '+92 42 3765432',
            'email' => 'accounts@crescenttours.pk',
            'city' => 'Lahore',
            'commission_plan' => 'Standard — 2.25% + PKR 500 flat per issued ticket',
            'incentive_type' => 'mixed',
            'total_bookings' => 612,
            'monthly_sales' => 22180000,
            'outstanding_balance' => 0,
            'status' => 'active',
            'joined_at' => '2023-08-01',
            'last_booking_at' => '2026-05-01 16:22',
            'notes' => 'Family and Umrah segments; prefers PIA/SV inventory.',
        ],
        [
            'agent_code' => 'AGT-1003',
            'agency_name' => 'Harbor Travel & Visa',
            'contact_person' => 'Faisal Rahman',
            'phone' => '+92 21 35677889',
            'email' => 'f.rahman@harbortravel.pk',
            'city' => 'Karachi',
            'commission_plan' => 'Starter — 2.0% on net fare after airline fees',
            'incentive_type' => 'percentage',
            'total_bookings' => 94,
            'monthly_sales' => 3100000,
            'outstanding_balance' => 185000,
            'status' => 'pending',
            'joined_at' => '2026-04-18',
            'last_booking_at' => null,
            'notes' => 'Onboarding KYC complete; awaiting finance sign-off for credit.',
        ],
        [
            'agent_code' => 'AGT-1004',
            'agency_name' => 'Capital Fly Consultants',
            'contact_person' => 'Sana Mir',
            'phone' => '+92 51 2876543',
            'email' => 'sana@capitalfly.pk',
            'city' => 'Islamabad',
            'commission_plan' => 'Corporate — negotiated 1.75% + volume rebate',
            'incentive_type' => 'percentage',
            'total_bookings' => 201,
            'monthly_sales' => 9650000,
            'outstanding_balance' => 120000,
            'status' => 'active',
            'joined_at' => '2025-01-20',
            'last_booking_at' => '2026-04-28 11:05',
            'notes' => 'NDC-heavy; technical contact for API errors: secondary email on file.',
        ],
        [
            'agent_code' => 'AGT-1005',
            'agency_name' => 'Ravi Express Holidays',
            'contact_person' => 'Imran Qureshi',
            'phone' => '+92 42 3889900',
            'email' => 'imran@raviexpress.pk',
            'city' => 'Lahore',
            'commission_plan' => 'Fixed PKR 1,200 per sector on domestic',
            'incentive_type' => 'fixed',
            'total_bookings' => 55,
            'monthly_sales' => 890000,
            'outstanding_balance' => 0,
            'status' => 'suspended',
            'joined_at' => '2025-06-10',
            'last_booking_at' => '2026-02-14 08:30',
            'notes' => 'Suspended pending settlement of aged receivables — demo scenario.',
        ],
        [
            'agent_code' => 'AGT-1006',
            'agency_name' => 'Blue Horizon Agencies',
            'contact_person' => 'Ayesha Lodhi',
            'phone' => '+92 300 7788990',
            'email' => 'ayesha@bluehorizon.pk',
            'city' => 'Karachi',
            'commission_plan' => 'Gold tier — 3.0% default on published fare',
            'incentive_type' => 'percentage',
            'total_bookings' => 318,
            'monthly_sales' => 14200000,
            'outstanding_balance' => 640000,
            'status' => 'active',
            'joined_at' => '2024-11-05',
            'last_booking_at' => '2026-05-02 13:18',
            'notes' => 'High volume EK/FZ; monitor outstanding against credit cap.',
        ],
    ],
];
