<?php

/**
 * Demo-only internal staff dataset (no DB).
 */
return [
    'demo_note' => 'Staff accounts help the OTA owner delegate booking operations without giving full admin access.',

    'staff' => [
        [
            'staff_code' => 'STF-001',
            'full_name' => 'Ayesha Malik',
            'role_title' => 'Senior Reservations Officer',
            'department' => 'Reservations',
            'phone' => '+92 300 1122334',
            'email' => 'ayesha.malik@ota-demo.local',
            'permissions_group' => 'Reservations — Full',
            'assigned_tasks' => ['Queue triage', 'Complex reissues', 'VIP follow-up'],
            'handled_bookings' => 1842,
            'status' => 'active',
            'joined_at' => '2022-06-01',
            'last_active_at' => '2026-05-03 08:15',
            'notes' => 'Shift lead Mon–Wed; trains new hires on GDS shortcuts.',
        ],
        [
            'staff_code' => 'STF-002',
            'full_name' => 'Bilal Hussain',
            'role_title' => 'Ticketing Specialist',
            'department' => 'Operations',
            'phone' => '+92 321 9988776',
            'email' => 'bilal.hussain@ota-demo.local',
            'permissions_group' => 'Operations — Ticketing',
            'assigned_tasks' => ['EMD issuance', 'Schedule changes', 'Refund queue'],
            'handled_bookings' => 1205,
            'status' => 'active',
            'joined_at' => '2023-02-14',
            'last_active_at' => '2026-05-02 19:40',
            'notes' => 'Preferred contact for airline ADM disputes.',
        ],
        [
            'staff_code' => 'STF-003',
            'full_name' => 'Fatima Noor',
            'role_title' => 'Customer Support Lead',
            'department' => 'Support',
            'phone' => '+92 333 4455667',
            'email' => 'fatima.noor@ota-demo.local',
            'permissions_group' => 'Support — Lead',
            'assigned_tasks' => ['Escalations', 'SLA reporting', 'Agent callbacks'],
            'handled_bookings' => 756,
            'status' => 'on_leave',
            'joined_at' => '2021-11-08',
            'last_active_at' => '2026-04-15 12:00',
            'notes' => 'Annual leave until 2026-05-20; backup: STF-006.',
        ],
        [
            'staff_code' => 'STF-004',
            'full_name' => 'Omar Siddiqui',
            'role_title' => 'Finance & Settlement',
            'department' => 'Finance',
            'phone' => '+92 51 5550199',
            'email' => 'omar.siddiqui@ota-demo.local',
            'permissions_group' => 'Finance — Read-only bookings',
            'assigned_tasks' => ['Agent statements', 'Supplier reconciliation'],
            'handled_bookings' => 312,
            'status' => 'active',
            'joined_at' => '2024-01-10',
            'last_active_at' => '2026-05-03 07:55',
            'notes' => 'No GDS write; views bookings for invoicing only.',
        ],
        [
            'staff_code' => 'STF-005',
            'full_name' => 'Zara Khan',
            'role_title' => 'Junior Reservations',
            'department' => 'Reservations',
            'phone' => '+92 345 2233445',
            'email' => 'zara.khan@ota-demo.local',
            'permissions_group' => 'Reservations — Junior',
            'assigned_tasks' => ['Simple PNRs', 'Seat requests', 'Queue monitoring'],
            'handled_bookings' => 428,
            'status' => 'inactive',
            'joined_at' => '2025-08-01',
            'last_active_at' => '2026-03-01 17:30',
            'notes' => 'Account suspended pending HR clearance (probation review).',
        ],
        [
            'staff_code' => 'STF-006',
            'full_name' => 'Hassan Raza',
            'role_title' => 'Support Agent',
            'department' => 'Support',
            'phone' => '+92 312 6677889',
            'email' => 'hassan.raza@ota-demo.local',
            'permissions_group' => 'Support — Standard',
            'assigned_tasks' => ['Inbound chat', 'Email tickets', 'Booking status checks'],
            'handled_bookings' => 591,
            'status' => 'active',
            'joined_at' => '2024-09-20',
            'last_active_at' => '2026-05-03 09:02',
            'notes' => 'Covering Fatima’s escalations during leave.',
        ],
    ],
];
